---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat:
      repo: https://github.com/simp/puppetlabs-concat
      ref: 5.3.0
    haveged: https://github.com/simp/pupmod-simp-haveged
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    selinux_core: https://github.com/puppetlabs/puppetlabs-selinux_core
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
  symlinks:
    rsync: "#{source_dir}"
