---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: simp-master
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: simp-master
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat
      branch: master
      #repo: https://github.com/simp/puppetlabs-concat
      #branch: simp-master
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      branch: simp-master
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    rsync: "#{source_dir}"
